### ISSUE TITLE
how to track a purchase?

### ISSUE THREAD

**Issue by ralyodio** [beyonk-adventures/svelte-facebook-pixel#3]
fbq("Purchase", { currency, value });

getting this warning

`fbq('Purchase', ...);" is not a valid fbq command.`

**Comment by antony** [comment]
Did you try

```js
fb.track('Purchase', { currency, value })
```

**Comment by dextermb** [comment]
Hi currently as stated above you can use the [`Purchase` event](https://developers.facebook.com/docs/meta-pixel/implementation/marketing-api/#purchase)
