### ISSUE TITLE
I sended parameters event_id and this result "_removed_" can u help?

### ISSUE THREAD

**Issue by imfarisi** [beyonk-adventures/svelte-facebook-pixel#6]
![image](https://user-images.githubusercontent.com/10131181/147730317-d6ca9209-a616-4071-8c6b-3002d11e503c.png)
What should i do?

![image](https://user-images.githubusercontent.com/10131181/147730367-e933bdbe-3bf2-459a-a215-a10397281a98.png)
i look at facebook pixel helper all data was sended

**Comment by dextermb** [comment]
Hi this is probably for security reasons. Please consult the documentation. We do not change any data you pass into `track`.
