### ISSUE TITLE
Can't use the package because of JSX

### ISSUE THREAD

**Issue by notkojak** [beyonk-adventures/svelte-facebook-pixel#7]
Hello, i can't use it for the moment with sveltekit, i have this error :

![image](https://user-images.githubusercontent.com/97678364/159008850-f00ad347-9e15-4978-8fa5-e7582e9ac33f.png)

If you can help me, thanks!

**Comment by dextermb** [comment]
Hi over the next couple of days we will be refactoring this package. If you're still having this issue afterwards please re-open this issue.
