### ISSUE TITLE
SvelteKit TS / Support

### ISSUE THREAD

**Issue by Kublick** [beyonk-adventures/svelte-facebook-pixel#9]
Hello

I tried to use this package with Svelte Kit with TS.

are there plans to add support to it ?

The errors I got.
1. There was no default export, solved it with { }
2. There are no definition files, kind of did a work around on it.
3. After following the instruction I was getting that fb was not a function, noticed there is an export of fb, I tried to call it but the pixel didnt fire up.

**Comment by Sebight** [comment]
Did you manage to make it work in the end, or not?
